From yourimage
MAINTAINER meimeidebiaobiao
RUN echo -e '#!/bin/sh\nservice apache2 start\n/bin/bash' >/etc/apache2/auto_service.sh &&\
         chmod 777 /etc/apache2/auto_service.sh

CMD [ "/bin/sh","/etc/apache2/auto_service.sh"]
